function word_box_create(){
	instance_create_layer(160,512,"Instances",wordbox,{text : FIVE})
	instance_create_layer(160,560,"Instances",wordbox,{text : TEN})
	instance_create_layer(160,608,"Instances",wordbox,{text : FIFTEEN})
	instance_create_layer(352,496,"Instances",wordbox,{text : TWO})
	instance_create_layer(352,544,"Instances",wordbox,{text : THREE})
	instance_create_layer(352,592,"Instances",wordbox,{text : FOUR})
	instance_create_layer(352,640,"Instances",wordbox,{text : SIX})
	instance_create_layer(544,512,"Instances",wordbox,{text : ONE})
	instance_create_layer(544,560,"Instances",wordbox,{text : TWENTY})
	instance_create_layer(544,608,"Instances",wordbox,{text : FOURHUNDRED})
	instance_create_layer(736,512,"Instances",wordbox,{text : PB20})
	instance_create_layer(736,560,"Instances",wordbox,{text : PB400})
	instance_create_layer(736,608,"Instances",wordbox,{text : ALMOST})
}